modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Ellpeck/NaturesStarlight"
license="MIT"
[[mods]]
modId="naturesstarlight"
version="${file.jarVersion}"
displayName="Nature's Starlight"
authors="Ellpeck"
description='''
Commission for Flabort'''